### ISSUE TITLE
Lock down JoinPart

### ISSUE THREAD

**Issue by elazar** [phergie/phergie-freenode#1]
Presently, any user can command the bot to join or part a channel. We should probably lock this down to channel owners, admins, and ops. See the documentation for the EventFilter plugin's [UserModeFilter](https://github.com/phergie/phergie-irc-plugin-react-eventfilter#usermodefilter) for details.

**Comment by svpernova09** [comment]
:+1:

**Comment by svpernova09** [comment]
resolved in b5faf93b0299eeebbac309ba7c118363d41321ee
